### ISSUE TITLE
Creates C:\program directory

### ISSUE THREAD

**Issue by Nayzal** [zetaPRIME/MultiBound2#12]
MultiBound2 seems to store mods in a folder called "program" directly in the C drive. Windows doesn't seem to like this, saying to rename it or that it could cause issues with other programs.

**Comment by Haano137** [comment]
It actually stores mods in "C:\Users\[USER_NAME]\AppData\Local\multibound\steamapps\workshop\content\211820". No clue why it does that in your case.

**Comment by Doodlinka** [comment]
same issue, it creates a "steamapps" folder in the program folder

**Comment by foxiepaws** [comment]
confirmed on win11.

**Comment by zetaPRIME** [comment]
apparently steamcmd requires quotes for paths with spaces on a command that only takes a single parameter???
anyway, attempting to fix with https://github.com/zetaPRIME/MultiBound2/commit/6507ae5a37356b25ee5b6fa39e9978163c6b45ab

**Comment by zetaPRIME** [comment]
probably fixed, but also made irrelevant with [v0.6.0](https://github.com/zetaPRIME/MultiBound2/releases/tag/v0.6.0) as unfortunately steamcmd integration would need either a complete redesign or change in external situation to be workable.
