### ISSUE TITLE
Missing decryption key(?) (v0.5.5)

### ISSUE THREAD

**Issue by Haano137** [zetaPRIME/MultiBound2#13]
![image](https://user-images.githubusercontent.com/71540568/178789410-a3cfcec9-d52f-4b8b-84e8-ec81e6ba5f18.png)
Still managed to get this error despite already having downloaded my fair share of workshop mods, starbound and otherwise.

**Comment by Haano137** [comment]
Band aid solution for windows:

1. Go here **C:/Users/<USERNAME>/AppData/Local/multibound/steamcmd**
2. Run the steamcmd.exe that's in the folder
3.  Run these commands:
- force_install_dir C:/Users/<USERNAME>/AppData/Local/multibound
- login <steam username> <steam password> <steam guard code if prompted>
4. Download a steam workshop mod by running this command **workshop_download_item 211820 <workshop mod id>**.
5. Exit the cmd by using the **quit** command or just by closing it like any other program.

After this, multibound 2 will run as intended.

**Comment by Umbrozium** [comment]
Downloading a workshop mod by running the command you provided results in failure on my side. As for the reason, I'm not sure.

**Comment by banoargeek** [comment]
> Downloading a workshop mod by running the command you provided results in failure on my side. As for the reason, I'm not sure.

You have to provide a mod ID for steamCMD to download, otherwise it just defaults to 0, and there is no mod with ID 0.

**Comment by banoargeek** [comment]
I am having the same issue:

Windows 10 Home Ed.

Perhaps the fact that I have a custom Steam install location is affecting multibound2? I tried the force_install_dir, logging in, and installing a mod to get the decryption key like @Haano137 recommended, however mutlibound2 still cannot find the key.

Can I somehow supply the decryption key manually to the software? Any advice is appreciated, thanks. :)

**Comment by Umbrozium** [comment]
> > Downloading a workshop mod by running the command you provided results in failure on my side. As for the reason, I'm not sure.
> 
> You have to provide a mod ID for steamCMD to download, otherwise it just defaults to 0, and there is no mod with ID 0.

Yeah I did provide the ID, the issue was a bit different, but I fixed it.

**Comment by Umbrozium** [comment]
> I am having the same issue:
> 
> Windows 10 Home Ed.
> 
> Perhaps the fact that I have a custom Steam install location is affecting multibound2? I tried the force_install_dir, logging in, and installing a mod to get the decryption key like @Haano137 recommended, however mutlibound2 still cannot find the key.
> 
> Can I somehow supply the decryption key manually to the software? Any advice is appreciated, thanks. :)

I tried to search for something like that, but no info about it seems to be available.

**Comment by banoargeek** [comment]
Yeah, I'm having the same problem. My guess is that the software is looking for the default Program Files installation for Steam / my Steam Library instead of my custom one, which is on another drive.

**Comment by Haano137** [comment]
> 

Yeah, tried that myself and looks like that success was more or less a fluke on my part. Couldn't replicate the steps on how I got it working so there's that.

**Comment by banoargeek** [comment]
I'm not willing to migrate a terabyte of steam library data to test this lol. Virtual machine maybe?

**Comment by Haano137** [comment]
> Yeah, I'm having the same problem. My guess is that the software is looking for the default Program Files installation for Steam / my Steam Library instead of my custom one, which is on another drive.

Currently, what I do now is use the Multibound 2 update and load instances, rather than downloading workshop mods; granted, you have to shut down Steam after downloading the mods and before running Multibound since running both Steam and Multibound will force all mods to load.

**Comment by banoargeek** [comment]
So I need to download all my mods, copy them to the instance's mod folder, close steam, and run multibound?

**Comment by banoargeek** [comment]
I'll be honest, I don't know a lot about manually creating an instance.

**Comment by Haano137** [comment]
> So I need to download all my mods, copy them to the instance's mod folder, close steam, and run multibound?
> 
> Do let me know if I have the right understanding here.

You need to copy the workshop mods to your instance's mod folder, you just have to close steam. Also creating a manual instance is pretty simple. While using a collection is the easiest way of making an instance, you could just open the instance.json with any text editor and turn this block of code from this:
![image](https://user-images.githubusercontent.com/71540568/183051926-be9f8629-31d2-436c-a02d-29342d56d208.png)
into something like this:
![image](https://user-images.githubusercontent.com/71540568/183052007-713adc62-b238-4fe6-9915-acf7f4b71c05.png)
and you'll be free to add any kind of mod you see fit; granted, steam in still turned off

**Comment by banoargeek** [comment]
Yeah, it definitely seems like a collection is better.

**Comment by banoargeek** [comment]
> You don't need to copy the workshop mods to your instance's mod folder, you just have to close steam.

I'm not sure if I'm repeating myself here, but closing Steam doesn't solve the problem. It still cannot update.

**Comment by banoargeek** [comment]
If I understand correctly, it doesn't matter how I configure my instance.json if multibound2 cannot decrypt and update the addons. I've tried manually placing mods in the instance's mod folder and that doesn't seem to work either. Perhaps I had to configure the json for that?

Sorry for all the confusion.

**Comment by zetaPRIME** [comment]
To manually pull the key:
- Open `<steam path>/config/config.vdf` in your text editor of choice
- Search for `211820`; you should find a section with that name, with an attribute called `DecryptionKey` inside.
- Copy that 64-digit hex string; open your MultiBound config file (`config.json` somewhere in your appdata folder if on windows) and insert that value as `workshopDecryptionKey`

**Comment by banoargeek** [comment]
Awesome, thank you ^^

**Comment by banoargeek** [comment]
Well, now we know how to get the decryption key, just need to figure out why else it won't update.

**Comment by Umbrozium** [comment]
> Well, now we know how to get the decryption key, just need to figure out why else it won't update.

![image](https://user-images.githubusercontent.com/38528831/183246112-5e8db5f3-2efc-4619-90e7-e3e3e733261c.png)
yeah, it ain't helping. i fetched my decryption key but it still gives me this error, even with the "bandaid" solution that @Haano137 provided.

**Comment by banoargeek** [comment]
> > Well, now we know how to get the decryption key, just need to figure out why else it won't update.
> 
> ![image](https://user-images.githubusercontent.com/38528831/183246112-5e8db5f3-2efc-4619-90e7-e3e3e733261c.png) yeah, it ain't helping. i fetched my decryption key but it still gives me this error, even with the "bandaid" solution that @Haano137 provided.

Yeah, wish I knew what else to try.

**Comment by zetaPRIME** [comment]
... yeah, I should probably add some better logging for this @.@

**Comment by banoargeek** [comment]
It's okay, just let us know if we can provide any more info

**Comment by robbieradiant** [comment]
i got this error but nothing was actually wrong, i just ignored it, manually added a mods folder with some non-workshop mods, and it booted up completely fine.

**Comment by banoargeek** [comment]
@Haano137 I noticed that you posted about Chucklefish denying anonymous mod downloads, does that affect Steam?

**Comment by Haano137** [comment]
> @Haano137 I noticed that you posted about Chucklefish denying anonymous mod downloads, does that affect Steam?
> 
> Sorry if it's a stupid question.

Must have mistaken me for someone else, I don't really remember posting anything about that, I could still give you an answer. Anyways, Steam has a developer feature that allows whether or not an anonymous account to download workshop files; which this Starbound mod client utilized. Someday, Chucklefish thought it was a good idea to turn that feature off, screwing over non-steam Starbound owners(gog.com, etc. etc.) and making it more difficult for Steam copy users like me to load multiple mod profiles.

**Comment by banoargeek** [comment]
> > @Haano137 I noticed that you posted about Chucklefish denying anonymous mod downloads, does that affect Steam?
> > Sorry if it's a stupid question.
> 
> Must have mistaken me for someone else, I don't really remember posting anything about that, I could still give you an answer. Anyways, Steam has a developer feature that allows whether or not an anonymous account to download workshop files; which this Starbound mod client utilized. Someday, Chucklefish thought it was a good idea to turn that feature off, screwing over non-steam Starbound owners(gog.com, etc. etc.) and making it more difficult for Steam copy users like me to load multiple mod profiles.

So, essentially we'd have to be logged in via steamCMD to fetch content properly?

**Comment by RisingManes** [comment]
> So, essentially we'd have to be logged in via steamCMD to fetch content properly? (Assuming that multibound accounts for this in future)

I'm afraid this is the case. My server has had to make a Steam account just to manage this one Starbound server.

**Comment by zetaPRIME** [comment]
Nothing needs to be logged in, steamcmd just needs to have the decryption key in the proper place in order to fetch content. Things *could* be failing for a different reason, or it could be a case of something getting gummed up with steamcmd.

**Comment by banoargeek** [comment]
Yeah, I tried it with just three mods and it doesn't want to fetch them

> Nothing needs to be logged in, steamcmd just needs to have the decryption key in the proper place in order to fetch content. Things _could_ be failing for a different reason, or it could be a case of something getting gummed up with steamcmd.

**Comment by zetaPRIME** [comment]
... valve has changed something on their end to make my previously working method not work anymore. steamcmd just refuses, encryption key or no, and I have no idea how to work around whatever is going on here.

**Comment by banoargeek** [comment]
> ... valve has changed something on their end to make my previously working method not work anymore. steamcmd just refuses, encryption key or no, and I have no idea how to work around whatever is going on here.

It's okay, take your time ^^

**Comment by zetaPRIME** [comment]
Notably, anything that any Steam account on the system has ever been subscribed to seems to work, no matter what I do to the files?? Anything else, Nope(tm)

**Comment by ComputerErika** [comment]
would loging in through steamcmd manually and then replacing the "anonymous" with the given username work?
I edited the "steamcmd2.txt" file to use my login after loging in through the steamcmd manually and ran it and it seems to work

**Comment by ComputerErika** [comment]
Uh I have no idea what I did, but this whole this whole thing just worked,
It might've been cause I exited steam before messing with the program? Or maybe using it as admin? Or maybe loging in to steamcmd and not loging out correctly? Im not sure but if I figure out more concrete steps Ill put it here unless someone has a better place?

**Comment by KaiCodeTraveler** [comment]
I got the Missing depiction key issue when I tried to add one particular mod in the already existing collection, and update my instance in Multibound 2 afterward...
Before that I got no real issues

**Comment by zetaPRIME** [comment]
have had to disable steamcmd support entirely due to the aforementioned changes to the workshop (I'm not willing to have MultiBound ask for your steam password). we'll see if the situation ever changes.
