### ISSUE TITLE
Asset Sources Usage

### ISSUE THREAD

**Issue by Nahere** [zetaPRIME/MultiBound2#15]
With Multibound 1, I could subscribe to various quality of life mods that I wanted in all my instances and include them with a blank blacklist like so:
```
"assetSources" : [
		{
			"type" : "workshop",
			"blacklist" : [
			]
		}  
    ]
```
Is this still possible in Multibound 2?
Also is there any documentation on the instance.json format anywhere? I notice windowTitle doesn't seem to do anything anymore.

**Comment by zetaPRIME** [comment]
windowTitle works on my end; there's no blanket "pull in everything from the workshop" option due to how workshop mods necessarily have to work (subscribing to everything used by any of your instances)
