### ISSUE TITLE
Manually installed mods

### ISSUE THREAD

**Issue by Sparkyboi5** [zetaPRIME/MultiBound2#16]
Is there a way to make manually installed mods (the ones you usually put in the "mods" folder, also known for being Zip files instead of Pak) work on a specific instance?

**Comment by Haano137** [comment]
Open Multibound 2 and right-click the profile you want to put mods in. Select "Open Instance directory", in there if there is no "mods" folder create one then place your mods in that folder.

**Comment by Sparkyboi5** [comment]
Already tried doing that, but it doesn't seem to work, i'll try by installing another mod and see if it works that way

**Comment by zetaPRIME** [comment]
if this issue is still at all relevant, also make sure that `inst:/mods/` is an `assetSources` entry (though it should be by default in every case).

**Comment by Sparkyboi5** [comment]
Quick question, how do i make sure that inst:/mods/ is an assetSources entry?
