### ISSUE TITLE
Failed To Download Mods

### ISSUE THREAD

**Issue by MarbleOcelott** [zetaPRIME/MultiBound2#17]
After trying to make an instance I was given the error "Failed to download one or more mods. This may be due to Steam maintenance, or due to a missing decryption key. (If you have the Steam version of Starbound, you should have this if your machine has ever downloaded a workshop mod.)" I understand what the error is telling me I just don't understand how to fix the issue, and I should have a decryption key as I have modded Steam Starbound through normal means before.

**Comment by zetaPRIME** [comment]
Steam changed something on their backend; mod downloading doesn't work unless you log into steamcmd and I'm not sure how I'd want to implement UI for prompting for that.

**Comment by zetaPRIME** [comment]
closing since steamcmd integration has been disabled pending any possibility of a solution.
