### ISSUE TITLE
Running Multibound 2 on steam using the %command% launch parameter causes Starbound to load all workshop mods. (v0.5.5)

### ISSUE THREAD

**Issue by Haano137** [zetaPRIME/MultiBound2#18]
Mutlibound 2 also seems to creating a "program" folder in my C:\ drive, which my Windows 10 doesn't like.

**Comment by zetaPRIME** [comment]
the `C:\Program` bug is both fixed and made irrelevant in v0.6.0 due to the removal of steamcmd integration; Starbound loading all workshop mods is a Starbound thing that I can't remedy. Might be possible to work around it in OpenStarbound in a future release.
