### ISSUE TITLE
Workshop downloading with `steamcmd`

### ISSUE THREAD

**Issue by zetaPRIME** [zetaPRIME/MultiBound2#3]
(this issue is mostly implementation notes)

On Windows, during startup, download and extract steamcmd from official link (`https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip`) if not already present

Support updating (and loading) both subscribed steam mods, and ones that aren't handled by steam
(handled separately because the latter will potentially be uninstalled by steam if put in the same place)

some relevant commands:
`login anonymous`
`force_install_dir` (makes a `steamapps` directory within)
`workshop_download_item 211820 <id>`

perhaps do this automatically after updating from collection if steamcmd is present and enabled

**Comment by zetaPRIME** [comment]
Implemented with commits 733ad37187b3396ac8067bae9924b80e57fb13cd through e290cbc14332045102923a8e78797e25a9aeebae.

**Comment by thakyZ** [comment]
Please don't use `login anonymous` It will not let you download any workshop items, you have to be logged into an account that owns Starbound.
