### ISSUE TITLE
multibound.exe - System Error

### ISSUE THREAD

**Issue by Hotmud9** [zetaPRIME/MultiBound2#8]
Attempting to run Multibound results in this pop-up:
"The code execution cannot proceed because MSVCP140_1.ddl was not found. Reinstalling the program may fix this problem."
I have reinstalled multiple times, to no avail.

**Comment by Febilian** [comment]
For the sake of anyone else who's experienced this and stuck, I was able to fix this by installing both the 64x and 86x versions of Visual C++ on my computer.

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by Hotmud9** [comment]
Thanks, Febilian! I'll go ahead and close the issue now.
